CREATE TABLE ORDERS
(
    ORDER_ID INTEGER NOT NULL,
    NAME VARCHAR(64),
    STRUCTURE VARCHAR(128),
    CUSTOMER VARCHAR(128) NOT NULL,
    VK VARCHAR(128) NOT NULL,
    DUE_DATE DATE NOT NULL,
    EVENT_DATE DATE NOT NULL,
    DESCRIPTION VARCHAR(1024)
);
CREATE TABLE SETTINGS
(
    LAST_ORDER_ID INTEGER DEFAULT 0 NOT NULL
);
